const ActionTypes = {
FETCH_USERS_LIST: 'FETCH_USERS_LIST',
GET_USERS_LIST: 'SET_USERS_LIST',
UPDATE_USER: 'UPDATE_USER',
SELECT_USER: 'SELECT_USER',
DELETE_USER: 'DELETE_USER',
DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
DELETE_ALL_SELECTED_USER: 'DELETE_ALL_SELECTED_USER',
}
export default ActionTypes;