const ActionTypes = {
FETCH_USERS_LIST: 'FETCH_USERS_LIST',
SET_FILTERED_LIST: 'SET_FILTERED_LIST',
UPDATE_USER: 'UPDATE_USER',
SELECT_USER: 'SELECT_USER',
DELETE_USER: 'DELETE_USER',
DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
DELETE_ALL_SELECTED_USER: 'DELETE_ALL_SELECTED_USER',
PAGINATION_CURRENT_PAGE: 'PAGINATION_CURRENT_PAGE',
}
export default ActionTypes;